export const NEWSLETTER_CONSENT_REMIND_LATER_TIMEOUT_MS = 3600000; // 1 hour in ms
export const NEWSLETTER_CONSENT_NEXT_DISPLAY_TIME_LOCALSTORAGE_KEY =
	'newsletter_consent_next_display_time';
export const NEWSLETTER_CONSENT_NEXT_DISPLAY_TIME_NEVER = -1;
export const NEWSLETTER_CONSENT_INPUT_CONTAINER_UNMOUNT_TIMEOUT_MS = 2500;
